pbk/Models/Enums/TestType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace pbk.Models.Enums
{
    public enum TestType
    {
        [Display(Name = "Show right answer after question")]
        ShowRightAnswerAfterQuestion = 0,
        [Display(Name = "Show right answers after test")]
        ShowRightAnswersAfterTest = 1
    }
}

pbk/Models/Test.cs
using pbk.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace pbk.Models
{
    public class Test
    {
        private ICollection<Question> questions;
        private ICollection<Test> children;
        
        public Test()
        {
            
            this.questions = new HashSet<Question>();
            this.children = new HashSet<Test>();
        }

        public Test(ICollection<Question> questions, TestType type, uint givenTime) : this()
        {
            this.questions = questions;
            this.Type = type;
            this.GivenTime = givenTime;
        }

        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        public TestType Type { get; set; }

        [Display(Name = "Given time in seconds")]
        public uint? GivenTime { get; set; }

        [Display(Name = "Parent test")]
        public int? ParentId { get; set; }

        public Test Parent { get; set; }

        public virtual ICollection<Question> Questions
        {
            get { return this.questions; }
            set { this.questions = value; }
        }

        public virtual ICollection<Test> Children
        {
            get { return this.children; }
            set { this.children = value; }
        }      
    }
}

pbk/Controllers/SubmissionAnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using pbk.Data;
using pbk.Models;

namespace pbk.Controllers
{
    public class SubmissionAnswersController : Controller
    {
        private readonly pbkContext _context;

        public SubmissionAnswersController(pbkContext context)
        {
            _context = context;
        }

        // GET: SubmissionAnswers
        public async Task<IActionResult> Index()
        {
            var pbkContext = _context.SubmissionAnswer.Include(s => s.Answer);
            return View(await pbkContext.ToListAsync());
        }

        // GET: SubmissionAnswers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var submissionAnswer = await _context.SubmissionAnswer
                .Include(s => s.Answer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (submissionAnswer == null)
            {
                return NotFound();
            }

            return View(submissionAnswer);
        }

        // GET: SubmissionAnswers/Create
        public IActionResult Create()
        {
            ViewData["AnswerId"] = new SelectList(_context.Answer, "Id", "Content");
            return View();
        }

        // POST: SubmissionAnswers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AnswerId,Id,Content")] SubmissionAnswer submissionAnswer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(submissionAnswer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AnswerId"] = new SelectList(_context.Answer, "Id", "Content", submissionAnswer.AnswerId);
            return View(submissionAnswer);
        }

        // GET: SubmissionAnswers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var submissionAnswer = await _context.SubmissionAnswer.FindAsync(id);
            if (submissionAnswer == null)
            {
                return NotFound();
            }
            ViewData["AnswerId"] = new SelectList(_context.Answer, "Id", "Content", submissionAnswer.AnswerId);
            return View(submissionAnswer);
        }

        // POST: SubmissionAnswers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AnswerId,Id,Content")] SubmissionAnswer submissionAnswer)
        {
            if (id != submissionAnswer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(submissionAnswer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubmissionAnswerExists(submissionAnswer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AnswerId"] = new SelectList(_context.Answer, "Id", "Content", submissionAnswer.AnswerId);
            return View(submissionAnswer);
        }

        // GET: SubmissionAnswers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var submissionAnswer = await _context.SubmissionAnswer
                .Include(s => s.Answer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (submissionAnswer == null)
            {
                return NotFound();
            }

            return View(submissionAnswer);
        }

        // POST: SubmissionAnswers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var submissionAnswer = await _context.SubmissionAnswer.FindAsync(id);
            _context.SubmissionAnswer.Remove(submissionAnswer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubmissionAnswerExists(int id)
        {
            return _context.SubmissionAnswer.Any(e => e.Id == id);
        }
    }
}

pbk/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using pbk.Data;
using pbk.Models;

namespace pbk.Controllers
{
    public class TestsController : Controller
    {
        private readonly pbkContext _context;

        public TestsController(pbkContext context)
        {
            _context = context;
        }

        // GET: Tests
        public async Task<IActionResult> Index()
        {
            var pbkContext = _context.Test.Include(t => t.Parent);
            return View(await pbkContext.ToListAsync());
        }

        // GET: Tests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Test
                .Include(t => t.Parent)
                .FirstOrDefaultAsync(m => m.Id == id);

            var Questions = _context.Test.Include(t => t.Questions).FirstOrDefault(t => t.Id == id);

            if (test == null)
            {
                return NotFound();
            }

            return View(test);
        }

        // GET: Tests/Create
        public IActionResult Create()
        {
            ViewData["ParentId"] = new SelectList(_context.Test, "Id", "Title");
            return View();
        }

        // POST: Tests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Type,GivenTime,ParentId")] Test test)
        {
            if (ModelState.IsValid)
            {
                _context.Add(test);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentId"] = new SelectList(_context.Test, "Id", "Title", test.ParentId);
            return View(test);
        }

        // GET: Tests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Test.FindAsync(id);
           
            if (test == null)
            {
                return NotFound();
            }
            ViewData["ParentId"] = new SelectList(_context.Test, "Id", "Title", test.ParentId);
            return View(test);
        }

        // POST: Tests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Type,GivenTime,ParentId")] Test test)
        {
            if (id != test.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(test);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TestExists(test.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentId"] = new SelectList(_context.Test, "Id", "Title", test.ParentId);
            return View(test);
        }

        // GET: Tests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Test
                .Include(t => t.Parent)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (test == null)
            {
                return NotFound();
            }

            return View(test);
        }

        // POST: Tests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var test = await _context.Test.FindAsync(id);
            _context.Test.Remove(test);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TestExists(int id)
        {
            return _context.Test.Any(e => e.Id == id);
        }
    }
}

pbk/Views/Tests/Create.cshtml
@using pbk.Models
@model pbk.Models.Test

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Test</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control" asp-items="@new SelectList(Enum.GetNames(typeof(pbk.Models.Enums.TestType)))"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GivenTime" class="control-label"></label>
                <input asp-for="GivenTime" class="form-control" />
                <span asp-validation-for="GivenTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParentId" class="control-label"></label>
                <select asp-for="ParentId" class="form-control" asp-items="ViewBag.ParentId">
                    <option selected="selected" disabled="disabled">Choose parent</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

pbk/Views/Tests/Delete.cshtml
@model pbk.Models.Test

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Test</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GivenTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GivenTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Parent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Parent.Title)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

pbk/Views/Tests/Details.cshtml
@model pbk.Models.Test

@{
    ViewData["Title"] = "Questions";
}

<h1>Questions of "@Html.DisplayFor(model => model.Title)" test.</h1>

<p>
    <a asp-action="Create" asp-controller="Questions" asp-route-testId="@Model.Id">Create New</a> |
    <a asp-action="Index" asp-controller="Tests">Back to List</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Condition
            </th>
            <th>
                Type
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Questions)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Condition)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id" asp-controller="Questions">Add answers</a> |
                    <a asp-action="Edit" asp-route-id="@item.Id" asp-controller="Questions">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" asp-controller="Questions">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

pbk/Views/Tests/Edit.cshtml
@model pbk.Models.Test


@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Test</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control" asp-items="@new SelectList(Enum.GetNames(typeof(pbk.Models.Enums.TestType)))"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GivenTime" class="control-label"></label>
                <input asp-for="GivenTime" class="form-control" />
                <span asp-validation-for="GivenTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParentId" class="control-label"></label>
                <select asp-for="ParentId" class="form-control" asp-items="ViewBag.ParentId"></select>
                <span asp-validation-for="ParentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

pbk/Views/Tests/Index.cshtml
@model IEnumerable<pbk.Models.Test>

@{
    ViewData["Title"] = "Tests";
}

    <h1>Tests</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GivenTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parent)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GivenTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Parent.Title)
            </td>
            <td>

                <a asp-action="Details" asp-route-id="@item.Id">Add Questions</a> |
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                <a asp-action="Create" asp-controller="SubmissionAnswers" asp-route-testId="@item.Id">Take</a>
            </td>
        </tr>
}
    </tbody>
</table>