pbk/Models/Enums/QuestionType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace pbk.Models.Enums
{
    public enum QuestionType
    {
        [Display(Name = "Many right answers")]
        ManyRightAnswers = 0,
        [Display(Name = "One right answer")]
        OneRightAnswer = 1,
        [Display(Name = "Need enter right answer")]
        NeedEnterRightAnswer = 2
    }
}

pbk/Models/Question.cs
using pbk.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace pbk.Models
{
    public class Question
    {
        private ICollection<Answer> answers;

        public Question()
        {
            //this.TestId = testId;
            this.answers = new HashSet<Answer>();
        }

        //public Question(int testId, string condition) : this(testId)
        public Question(string condition) : this()
        {
            this.Condition = condition;
        }

        public int Id { get; set; }

        [Required]
        public string Condition { get; set; }

        [Display(Name = "Test")]
        public int TestId { get; set; }

        public Test Test { get; set; }

        [Required]
        public QuestionType Type { get; set; }

        public virtual ICollection<Answer> Answers
        {
            get { return this.answers; }
            set { this.answers = value; }
        }
    }
}

pbk/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using pbk.Data;
using pbk.Models;

namespace pbk.Controllers
{
    public class AnswersController : Controller
    {
        private readonly pbkContext _context;

        public AnswersController(pbkContext context)
        {
            _context = context;
        }

        

        // GET: Answers/Create
        public IActionResult Create(int questionId)
        {
            var question = _context.Question.Find(questionId);

            ViewBag.QuestionId = questionId;
            ViewBag.QuestionCondition = question.Condition;
            return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Content,IsCorrect,QuestionId")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(answer);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Questions", new { Id = answer.QuestionId });
            }
            ViewData["QuestionId"] = new SelectList(_context.Question, "Id", "Condition", answer.QuestionId);
            return View(answer);
        }

        // GET: Answers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answer = await _context.Answer.FindAsync(id);
            if (answer == null)
            {
                return NotFound();
            }
            ViewData["QuestionId"] = new SelectList(_context.Question, "Id", "Condition", answer.QuestionId);
            return View(answer);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Content,IsCorrect,QuestionId")] Answer answer)
        {
            if (id != answer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(answer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnswerExists(answer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Questions", new { Id = answer.QuestionId });
            }
            ViewData["QuestionId"] = new SelectList(_context.Question, "Id", "Condition", answer.QuestionId);
            return View(answer);
        }

        // GET: Answers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answer = await _context.Answer
                .Include(a => a.Question)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (answer == null)
            {
                return NotFound();
            }

            return View(answer);
        }

        // POST: Answers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var answer = await _context.Answer.FindAsync(id);
            _context.Answer.Remove(answer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Questions", new { Id = answer.QuestionId });
        }

        private bool AnswerExists(int id)
        {
            return _context.Answer.Any(e => e.Id == id);
        }
    }
}

pbk/Controllers/QuestionsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using pbk.Data;
using pbk.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pbk.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly pbkContext _context;

        public QuestionsController(pbkContext context)
        {
            _context = context;
        }

        // GET: Questions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Question
                .Include(q => q.Test)
                .FirstOrDefaultAsync(m => m.Id == id);

            var Answers = _context.Question.Include(t => t.Answers).FirstOrDefault(t => t.Id == id);

            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // GET:Questions/Create
        public IActionResult Create(int testId)
        {
            var test = _context.Test.Find(testId);

            ViewBag.TestId = testId;
            ViewBag.TestTitle = test.Title;             

            return View();
        }

        // POST: Tests/Questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Condition,TestId,Type")] Question question)
        {
            if (ModelState.IsValid)
            {
                _context.Add(question);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), "Tests", new {Id = question.TestId});
            }
          
            return View(question);
        }

        // GET: Questions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Question.FindAsync(id);
            var Answers = _context.Question.Include(t => t.Answers).FirstOrDefault(t => t.Id == id);
            if (question == null)
            {
                return NotFound();
            }
            ViewData["TestId"] = new SelectList(_context.Test, "Id", "Title", question.TestId);
            return View(question);
        }

        // POST: Tests/Questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Condition,TestId,Type")] Question question)
        {
            if (id != question.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(question);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(question.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), "Tests", new { Id = question.TestId });
            }
            ViewData["TestId"] = new SelectList(_context.Test, "Id", "Title", question.TestId);
            return View(question);
        }

        // GET: Questions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Question
                .Include(q => q.Test)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var question = await _context.Question.FindAsync(id);
            _context.Question.Remove(question);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), "Tests", new { Id = question.TestId });
        }

        private bool QuestionExists(int id)
        {
            return _context.Question.Any(e => e.Id == id);
        }
    }
}

pbk/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using pbk.Data;
using pbk.Models;

namespace pbk.Controllers
{
    public class TestsController : Controller
    {
        private readonly pbkContext _context;

        public TestsController(pbkContext context)
        {
            _context = context;
        }

        // GET: Tests
        public async Task<IActionResult> Index()
        {
            var pbkContext = _context.Test.Include(t => t.Parent);
            return View(await pbkContext.ToListAsync());
        }

        // GET: Tests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Test
                .Include(t => t.Parent)
                .FirstOrDefaultAsync(m => m.Id == id);

            var Questions = _context.Test.Include(t => t.Questions).FirstOrDefault(t => t.Id == id);

            if (test == null)
            {
                return NotFound();
            }

            return View(test);
        }

        // GET: Tests/Create
        public IActionResult Create()
        {
            ViewData["ParentId"] = new SelectList(_context.Test, "Id", "Title");
            return View();
        }

        // POST: Tests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Type,GivenTime,ParentId")] Test test)
        {
            if (ModelState.IsValid)
            {
                _context.Add(test);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentId"] = new SelectList(_context.Test, "Id", "Title", test.ParentId);
            return View(test);
        }

        // GET: Tests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Test.FindAsync(id);
           
            if (test == null)
            {
                return NotFound();
            }
            ViewData["ParentId"] = new SelectList(_context.Test, "Id", "Title", test.ParentId);
            return View(test);
        }

        // POST: Tests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Type,GivenTime,ParentId")] Test test)
        {
            if (id != test.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(test);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TestExists(test.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentId"] = new SelectList(_context.Test, "Id", "Title", test.ParentId);
            return View(test);
        }

        // GET: Tests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Test
                .Include(t => t.Parent)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (test == null)
            {
                return NotFound();
            }

            return View(test);
        }

        // POST: Tests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var test = await _context.Test.FindAsync(id);
            _context.Test.Remove(test);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TestExists(int id)
        {
            return _context.Test.Any(e => e.Id == id);
        }
    }
}

pbk/Views/Questions/Create.cshtml
@model pbk.Models.Question

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Add question to "@ViewBag.TestTitle" test.</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TestId" value="@ViewBag.TestId" />
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <input asp-for="Condition" class="form-control" />
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control" asp-items="@new SelectList(Enum.GetNames(typeof(pbk.Models.Enums.QuestionType)))"></select>
                <span asp-validation-for="Type" class="text-danger" asp-route-id="@ViewBag.TestId"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="Tests"  asp-route-id="@ViewBag.TestId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

pbk/Views/Questions/Delete.cshtml
@model pbk.Models.Question

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Condition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Condition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Test)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Test.Title)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Details" asp-controller="Tests" asp-route-id="@Model.TestId">Back to List</a>
    </form>
</div>

pbk/Views/Questions/Details.cshtml
@model pbk.Models.Question

@{
    ViewData["Title"] = "Details";
}

<h1>Answers of "@Html.DisplayFor(model => model.Condition)" question.</h1>
<h1>Type of question is "@Html.DisplayFor(model => model.Type)".</h1>

<p>
    <a asp-action="Create" asp-controller="Answers" asp-route-questionId="@Model.Id">Create New</a> |
    <a asp-action="Details" asp-controller="Tests" asp-route-id="@Model.TestId">Back to List</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Content
            </th>
            <th>
                Correct answer
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Answers)
        {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Content)
            </td>
            <td>
                @Html.DisplayFor(model => item.IsCorrect)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" asp-controller="Answers">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" asp-controller="Answers">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

pbk/Views/Questions/Edit.cshtml
@model pbk.Models.Question

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="TestId" value="@Model.TestId"/>            
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <input asp-for="Condition" class="form-control" />
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control" asp-items="@new SelectList(Enum.GetNames(typeof(pbk.Models.Enums.QuestionType)))"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="Tests"  asp-route-id="@Model.TestId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}